version: 2
updates:
- package-ecosystem: nuget
  directory: "/Basta2019_Weather/Basta2019_WeatherAPI"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: 3rd-party-dependency-upgrade
